server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coldcase?currentSchema=users
    username: coldcase
    password: coldcase_dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: users
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
